# -*- coding: utf-8 -*-
"""Test 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tngBALQHA7lNYXZoy_4mYfiOKE3kBtC
"""

# check error in phone number column

# import data from file
# select phone number column
# check phone number
# check phone number length
# delete '-' sign
# check if phone number start with 001, delete the first zero
# check if number start with 011 must have 8 number
# check if number start other than 011 must have 7 number
#

from google.colab import files
import pandas as pd

uploaded = files.upload()

file_name = list(uploaded.keys())[0]

df = pd.read_excel(file_name)

df['Mobile Phone']

